/**
 * Core type definitions for the AI webpage generator.
 * These types define the data model for components, screens, and session state.
 */

/**
 * Represents a reusable UI component generated by the agent.
 * Components are the building blocks of screens.
 */
export interface Component {
  id: string;
  name: string;
  description: string;
  html: string;
  tailwindClasses?: string;
  lastUpdatedAt: Date;
}

/**
 * Layout types for screen composition.
 */
export type ScreenLayout = 
  | 'stack'           // All components stacked vertically (default)
  | 'sidebar-left'    // Sidebar on left, main content on right
  | 'sidebar-right'   // Sidebar on right, main content on left
  | 'holy-grail'      // Header, sidebar+content, footer
  | 'grid-2'          // 2-column grid
  | 'grid-3';         // 3-column grid

/**
 * Represents the current screen composition.
 * A screen is an ordered collection of components with layout info.
 */
export interface Screen {
  componentIds: string[];
  layout: ScreenLayout;
  layoutConfig?: {
    sidebarComponentId?: string;      // Which component is the sidebar
    headerComponentId?: string;       // Which component is the header
    footerComponentId?: string;       // Which component is the footer
    mainComponentIds?: string[];      // Which components go in main area
  };
}

/**
 * A design frame on the canvas - like an artboard in Figma.
 * Each frame is an independent design that can be positioned on the canvas.
 * IMPORTANT: Stores a SNAPSHOT of components to be independent of session state.
 */
export interface DesignFrame {
  id: string;
  name: string;
  screen: Screen;
  components: Component[];  // Snapshot of components - makes each frame independent!
  position: { x: number; y: number };
  size: { width: number; height: number };
  createdAt: Date;
  parentFrameId?: string;  // For branched/forked designs
}

/**
 * Canvas state for zoom/pan.
 */
export interface CanvasState {
  zoom: number;
  panX: number;
  panY: number;
}

/**
 * A message in the conversation history.
 */
export interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
}

/**
 * The complete session state, persisted in memory.
 */
export interface SessionState {
  id: string;
  messages: Message[];
  components: Map<string, Component>;
  screen: Screen | null;
  decisionHistory: DecisionHistoryEntry[];
  createdAt: Date;
  lastActivityAt: Date;
}

/**
 * Serializable version of SessionState for API responses.
 */
export interface SerializedSessionState {
  id: string;
  messages: Message[];
  components: Component[];
  screen: Screen | null;
  decisionHistory: DecisionHistoryEntry[];
}

/**
 * The action type the agent decides to take.
 */
export type AgentAction = 'REGENERATE_SCREEN' | 'UPDATE_COMPONENTS';

/**
 * Describes an update to be applied to a component.
 */
export interface ComponentUpdate {
  componentId: string;
  changeDescription: string;
}

/**
 * Describes a new component to be created.
 */
export interface NewComponentSpec {
  name: string;
  description: string;
  requirements: string;
  styleHints?: string;
}

/**
 * Layout specification in agent decisions.
 */
export interface LayoutSpec {
  type: ScreenLayout;
  sidebarComponent?: string;   // Name of sidebar component
  headerComponent?: string;    // Name of header component
  footerComponent?: string;    // Name of footer component
}

/**
 * The structured decision returned by the agent.
 */
export interface AgentDecision {
  action: AgentAction;
  rationale: string;
  createBranch?: boolean;      // If true, create a copy of the design before modifying
  updates?: ComponentUpdate[];
  newComponents?: NewComponentSpec[];
  screenOrder?: string[];
  regenerateSpecs?: NewComponentSpec[];
  layout?: LayoutSpec;         // How to arrange the components
}

/**
 * A decision entry with context for the history.
 */
export interface DecisionHistoryEntry {
  id: string;
  prompt: string;
  decision: AgentDecision;
  timestamp: Date;
  componentsAffected: string[];
}

/**
 * Result of a tool execution.
 */
export interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
}

/**
 * The response from the generate API.
 */
export interface GenerateResponse {
  success: boolean;
  session: SerializedSessionState;
  error?: string;
  agentRationale?: string;
  agentDecision?: AgentDecision;
  decisionHistory?: DecisionHistoryEntry[];
}
